language: python
python:
 - "2.5"
 - "2.6"
 - "2.7"
 - "2.8"
 - "3.0"
 - "3.1"
 - "3.2"
 - "3.3"
 - "3.2"
 - "3.4"
 - "pypy"
 - "pypy3"
 - "nightly" # Cython
install: "pip install -r tests/dev-requirements.txt"
script: "nosetests"
