site_name: Docbuilder
pages:
- [index.md, ReadMe]
- [docs/docbuilder.md, Docbuilder]
- [StyleGuide.md, Style Guide]
- [VariableNamingStyleGuide.md, Variable Naming Style Guide]
- [examples/helloworld.pylit.md, Example Hello World]
